version: '3'
services:
    liquidator:
        build: .
        environment:
            - CHAIN_ID=1
            - ETHEREUM_RPC_HTTP_URL=
            - ETHEREUM_RPC_WS_URL=
            - PRIVATE_KEY=
            - PROFIT_ASSET=USD
            - ETHGASSTATION_API_KEY=
        # persist the sqlite data to disk so we don't lose it
        # on rebuilds.
        volumes:
            - ./liquidator:/var/lib/liquidator/data
